
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label lblResult;

	private global::Gtk.Label lblRatioX;

	private global::Gtk.Entry txtBoxRatioX;

	private global::Gtk.Label lblRatioY;

	private global::Gtk.Entry txtBoxRatioY;

	private global::Gtk.Label lblResWidth;

	private global::Gtk.Entry txtBoxResWidth;

	private global::Gtk.Button btnCalcResWidth;

	private global::Gtk.Button btnCalcRatio;

	private global::Gtk.Label lblResHeight;

	private global::Gtk.Entry txtBoxResHeight;

	private global::Gtk.Label lblVersion;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 900;
		this.HeightRequest = 400;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Resolution Calc");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 1200;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblResult = new global::Gtk.Label();
		this.lblResult.WidthRequest = 400;
		this.lblResult.HeightRequest = 100;
		this.lblResult.Name = "lblResult";
		this.lblResult.Justify = ((global::Gtk.Justification)(2));
		this.fixed1.Add(this.lblResult);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblResult]));
		w1.X = 39;
		w1.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblRatioX = new global::Gtk.Label();
		this.lblRatioX.Name = "lblRatioX";
		this.lblRatioX.LabelProp = global::Mono.Unix.Catalog.GetString("ratio x:");
		this.fixed1.Add(this.lblRatioX);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblRatioX]));
		w2.X = 15;
		w2.Y = 89;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBoxRatioX = new global::Gtk.Entry();
		this.txtBoxRatioX.WidthRequest = 50;
		this.txtBoxRatioX.CanFocus = true;
		this.txtBoxRatioX.Name = "txtBoxRatioX";
		this.txtBoxRatioX.IsEditable = true;
		this.txtBoxRatioX.InvisibleChar = '•';
		this.fixed1.Add(this.txtBoxRatioX);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBoxRatioX]));
		w3.X = 67;
		w3.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblRatioY = new global::Gtk.Label();
		this.lblRatioY.Name = "lblRatioY";
		this.lblRatioY.LabelProp = global::Mono.Unix.Catalog.GetString("ratio y:");
		this.fixed1.Add(this.lblRatioY);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblRatioY]));
		w4.X = 150;
		w4.Y = 86;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBoxRatioY = new global::Gtk.Entry();
		this.txtBoxRatioY.WidthRequest = 50;
		this.txtBoxRatioY.CanFocus = true;
		this.txtBoxRatioY.Name = "txtBoxRatioY";
		this.txtBoxRatioY.IsEditable = true;
		this.txtBoxRatioY.InvisibleChar = '•';
		this.fixed1.Add(this.txtBoxRatioY);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBoxRatioY]));
		w5.X = 204;
		w5.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblResWidth = new global::Gtk.Label();
		this.lblResWidth.Name = "lblResWidth";
		this.lblResWidth.LabelProp = global::Mono.Unix.Catalog.GetString("pixel width:");
		this.fixed1.Add(this.lblResWidth);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblResWidth]));
		w6.X = 299;
		w6.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBoxResWidth = new global::Gtk.Entry();
		this.txtBoxResWidth.CanFocus = true;
		this.txtBoxResWidth.Name = "txtBoxResWidth";
		this.txtBoxResWidth.IsEditable = true;
		this.txtBoxResWidth.InvisibleChar = '•';
		this.fixed1.Add(this.txtBoxResWidth);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBoxResWidth]));
		w7.X = 385;
		w7.Y = 77;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnCalcResWidth = new global::Gtk.Button();
		this.btnCalcResWidth.CanFocus = true;
		this.btnCalcResWidth.Events = ((global::Gdk.EventMask)(256));
		this.btnCalcResWidth.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
		this.btnCalcResWidth.Name = "btnCalcResWidth";
		this.btnCalcResWidth.UseUnderline = true;
		this.btnCalcResWidth.Label = global::Mono.Unix.Catalog.GetString("Calculate Width");
		this.fixed1.Add(this.btnCalcResWidth);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCalcResWidth]));
		w8.X = 12;
		w8.Y = 141;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnCalcRatio = new global::Gtk.Button();
		this.btnCalcRatio.CanFocus = true;
		this.btnCalcRatio.Name = "btnCalcRatio";
		this.btnCalcRatio.UseUnderline = true;
		this.btnCalcRatio.Label = global::Mono.Unix.Catalog.GetString("Calculate Ratio");
		this.fixed1.Add(this.btnCalcRatio);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCalcRatio]));
		w9.X = 202;
		w9.Y = 139;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblResHeight = new global::Gtk.Label();
		this.lblResHeight.Name = "lblResHeight";
		this.lblResHeight.LabelProp = global::Mono.Unix.Catalog.GetString("pixel height:");
		this.fixed1.Add(this.lblResHeight);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblResHeight]));
		w10.X = 598;
		w10.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBoxResHeight = new global::Gtk.Entry();
		this.txtBoxResHeight.CanFocus = true;
		this.txtBoxResHeight.Name = "txtBoxResHeight";
		this.txtBoxResHeight.IsEditable = true;
		this.txtBoxResHeight.InvisibleChar = '•';
		this.fixed1.Add(this.txtBoxResHeight);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBoxResHeight]));
		w11.X = 685;
		w11.Y = 78;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblVersion = new global::Gtk.Label();
		this.lblVersion.Name = "lblVersion";
		this.lblVersion.LabelProp = global::Mono.Unix.Catalog.GetString("v. alpha 0.0");
		this.fixed1.Add(this.lblVersion);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblVersion]));
		w12.X = 768;
		w12.Y = 288;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnCalcResWidth.Pressed += new global::System.EventHandler(this.OnBtnCalcResWidthPressed);
		this.btnCalcRatio.Clicked += new global::System.EventHandler(this.OnBtnCalcRatioClicked);
	}
}
